ALTER TABLE PARTITE_SERIE_A
ADD COLUMN Stagione VARCHAR(20);

UPDATE PARTITE_SERIE_A
SET Stagione = CASE
    WHEN MONTH(Date) < 8 THEN CONCAT(CAST(YEAR(Date) - 1 AS CHAR), '/', CAST(YEAR(Date) AS CHAR))
    ELSE CONCAT(CAST(YEAR(Date) AS CHAR), '/', CAST(YEAR(Date) + 1 AS CHAR))
END;