CREATE TABLE Serie_A_giornate AS
SELECT 
Column1,
`Div`,
CEIL( (ROW_NUMBER() OVER (PARTITION BY stagione ORDER BY Date))/10) AS giornata,
Stagione,
Date,
HomeTeam,
AwayTeam,
FTHG AS ft_home_goals,
FTAG AS ft_away_goals,
FTR AS ft_result,
HTHG ht_home_goals,
HTAG ht_away_goals,
HTR ht_results,
HS home_shots,
`AS` AS away_shots,
HST AS home_shots_targ,
AST AS away_shots_targ,
HF AS home_fouls,
AF AS away_fouls,
HC home_corners,
AC away_corners,
HY home_yellow,
AY away_yellow,
HR home_red,
AR away_red,
B365H home_win_odds,
B365D draw_odds,
B365A away_win_odds
FROM PARTITE_SERIE_A PSA 